---
image: ruby:2.3.0
before_script:
  - apt-get update -qq && apt-get install -y -qq sqlite3 libsqlite3-dev nodejs wkhtmltopdf
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc

rspec:
  script:
    - bundle install
    - bundle exec rake db:setup RAILS_ENV=test
    - bundle exec rspec spec